services:
  - type: web
    name: oai-proxy
    env: docker
    repo: https://github.com/DergotYT/proxy.git
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./docker/render/Dockerfile   
